cv_scoring_task:
  description: >
    Evaluate each resume independently and assign a CV rating based on the criteria.
  expected_output: >
    A numerical score representing the resume's alignment with the predefined criteria.
  agent: cv_scorer

elo_comparison_task:
  description: >
    Perform pairwise comparisons of resumes to update their Elo scores.
  expected_output: >
    Updated Elo scores reflecting the relative strengths of the compared resumes.
  agent: elo_comparator

criteria_update_task:
  description: >
    Update the evaluation criteria and weights for a specific role.
  expected_output: >
    An updated criteria set stored in the database.
  agent: criteria_manager
